More changes.

diff --git a/.github/workflows/test-workflow.yml b/.github/workflows/test-workflow.yml
--- a/.github/workflows/test-workflow.yml
+++ b/.github/workflows/test-workflow.yml
@@ -5,11 +5,17 @@ jobs:
   test-job:
     runs-on: ubuntu-latest
     steps:
-      # - name: Checkout code
-      #   uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
       - name: Run workflow
         id: fourcalver
         uses: emptyother/action-fourcalver@v1
       - name: Show output
         run: |
           echo "Result: ${{ steps.fourcalver.outputs.result }}"
+      - name: Validate calver format
+        run: |
+          if [[ ! "${{ steps.fourcalver.outputs.result }}" =~ ^[0-9]{4}\.[0-9]{2}\.[0-9]{2}\.[0-9]+$ ]]; then
+            echo "Calver format invalid: ${{ steps.fourcalver.outputs.result }}"
+            exit 1
+          fi
